### ISSUE TITLE
VegaLite.push should validate the data

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/kino#11]
VegaLite.push does not validate the data, and if we send invalid data, it crashes the graph rendering.

My suggestion would be to call `Map.new(arg)` on whatever we pass to push. This will both validate it and allow us to pass keyword lists in.

Thoughts @jonatanklosko?

**Comment by jonatanklosko** [comment]
Alternatively we could have a guard, but `Map.new` sounds good, especially that it will error for structs. We should do the same for each element on `push_many`.

**Comment by josevalim** [comment]
I forgot about push_many but I would be inclined to say yes. Or we go the guard route.
